# Generated by Django 6.0.7 on 2026-07-31 05:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=20, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('edad', models.CharField(choices=[('cachorro', 'Cachorro'), ('joven', 'Joven'), ('adulto', 'Adulto')], max_length=20, verbose_name='Edad')),
                ('tamano', models.CharField(choices=[('pequeno', 'Pequeño'), ('mediano', 'Mediano'), ('grande', 'Grande')], max_length=20, verbose_name='Tamaño')),
                ('sexo', models.CharField(choices=[('macho', 'Macho'), ('hembra', 'Hembra')], max_length=20, verbose_name='Sexo')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('estado', models.CharField(choices=[('rescatado', 'Rescatado'), ('en_adopcion', 'En adopción'), ('adoptado', 'Adoptado')], default='rescatado', max_length=20, verbose_name='Estado')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='mascotas/', verbose_name='Foto principal')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='FotoMascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='mascotas/', verbose_name='Imagen')),
                ('orden', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='mascotas.mascota', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Foto de mascota',
                'verbose_name_plural': 'Fotos de mascotas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReportePerdido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=20, verbose_name='Especie')),
                ('raza', models.CharField(blank=True, max_length=100, verbose_name='Raza')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/perdidos/', verbose_name='Foto')),
                ('ultima_ubicacion', models.CharField(max_length=255, verbose_name='Última ubicación')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitud')),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitud')),
                ('fecha_perdida', models.DateField(verbose_name='Fecha de pérdida')),
                ('recompensa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Recompensa (Bs)')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto extra')),
                ('estado', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], default='perdido', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_perdidos', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte de mascota perdida',
                'verbose_name_plural': 'Reportes de mascotas perdidas',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='ReporteRescatado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(choices=[('perro', 'Perro'), ('gato', 'Gato'), ('otro', 'Otro')], max_length=20, verbose_name='Especie')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Color')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='mascotas/rescatados/', verbose_name='Foto')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('ubicacion', models.CharField(max_length=255, verbose_name='Dónde fue encontrado')),
                ('fecha_rescate', models.DateField(verbose_name='Fecha del rescate')),
                ('estado', models.CharField(choices=[('rescatado', 'Rescatado'), ('en_hogar', 'En hogar temporal')], default='rescatado', max_length=20, verbose_name='Estado')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_rescatados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Reporte de animal rescatado',
                'verbose_name_plural': 'Reportes de animales rescatados',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='SolicitudAdopcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(verbose_name='¿Por qué quieres adoptar?')),
                ('experiencia', models.TextField(blank=True, verbose_name='Experiencia con mascotas')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de solicitud')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='mascotas.mascota', verbose_name='Mascota')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_adopcion', to=settings.AUTH_USER_MODEL, verbose_name='Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitud de adopción',
                'verbose_name_plural': 'Solicitudes de adopción',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
