# Generated by Django 6.0.7 on 2026-08-21 02:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mascotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True, verbose_name='Fecha de inicio')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('finalizado', 'Finalizado'), ('alertado', 'Alertado'), ('cancelado', 'Cancelado')], default='activo', max_length=20, verbose_name='Estado')),
                ('observaciones_generales', models.TextField(blank=True, verbose_name='Observaciones generales')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('adoptante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to=settings.AUTH_USER_MODEL, verbose_name='Adoptante')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='mascotas.mascota', verbose_name='Mascota')),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimiento', to='mascotas.solicitudadopcion', verbose_name='Solicitud de adopción')),
            ],
            options={
                'verbose_name': 'Seguimiento post-adopción',
                'verbose_name_plural': 'Seguimientos post-adopción',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('visita_vencida', 'Visita vencida'), ('visita_proxima', 'Visita próxima'), ('checklist_no_aprobado', 'Checklist no aprobado'), ('maltrato_sospechoso', 'Maltrato sospechoso'), ('mascota_perdida', 'Mascota perdida'), ('otro', 'Otro')], max_length=30, verbose_name='Tipo')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='media', max_length=20, verbose_name='Prioridad')),
                ('mensaje', models.TextField(blank=True, verbose_name='Mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='Leída')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_resuelta', models.DateTimeField(blank=True, null=True, verbose_name='Fecha resuelta')),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='seguimiento.seguimiento', verbose_name='Seguimiento')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('telefonica', 'Telefónica')], max_length=20, verbose_name='Tipo de visita')),
                ('fecha_programada', models.DateTimeField(verbose_name='Fecha programada')),
                ('fecha_realizada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha realizada')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=20, verbose_name='Estado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to='seguimiento.seguimiento', verbose_name='Seguimiento')),
            ],
            options={
                'verbose_name': 'Visita',
                'verbose_name_plural': 'Visitas',
                'ordering': ['fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='ListaVerificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicion_vivienda', models.BooleanField(default=False, verbose_name='Condición de vivienda adecuada')),
                ('alimentacion_adecuada', models.BooleanField(default=False, verbose_name='Alimentación adecuada')),
                ('agua_disponible', models.BooleanField(default=False, verbose_name='Agua disponible')),
                ('atencion_veterinaria', models.BooleanField(default=False, verbose_name='Atención veterinaria al día')),
                ('identificacion_mascota', models.BooleanField(default=False, verbose_name='Identificación (collar/microchip)')),
                ('socializacion', models.BooleanField(default=False, verbose_name='Socialización adecuada')),
                ('comportamiento', models.BooleanField(default=False, verbose_name='Comportamiento sin signos de maltrato')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('aprobado', models.BooleanField(default=False, verbose_name='Aprobado')),
                ('fecha_verificacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de verificación')),
                ('visita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lista_verificacion', to='seguimiento.visita', verbose_name='Visita')),
            ],
            options={
                'verbose_name': 'Lista de verificación',
                'verbose_name_plural': 'Listas de verificación',
            },
        ),
    ]
